#!/usr/bin/env bash

# General Alias
alias rm='rm -vI'
alias mv='mv -iv'
alias cp='cp -iv'
alias mkdir='mkdir -pv'
alias vim='nvim'
alias v='fd --type f --hidden --exclude .git | fzf-tmux -p --reverse | xargs -I {} nvim {}'
alias sd="cd ~ && cd \$(find * -type d | fzf)"
alias nf='neofetch'
alias cc='clear'
alias df='df -h'
alias cat='bat'
alias free='free -m' # show sizes in MB
alias z='zathura'
alias ansibleupdate='just setup-all -K --ask-become-pass --ask-vault-pass'
alias fpu= 'flatpak update'

# Eza Alias
alias ll='eza --all --long --color=auto --icons --group-directories-first'
alias la='eza --grid --all --color auto --icons --sort=type'
alias lt='eza --tree --level=2 --icons'
alias ls='eza --grid --color auto --icons --sort=type'

# More Random Alias
alias conf='cd ~/.config'
alias yt="yt-dlp"

# Change directory aliases
alias home='cd ~'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Alias's for archives
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

# YADM Alias
alias y='yadm'
alias ya='yadm add'
alias ys='yadm status'
alias yd='yadm diff'

# Tmux Alias
alias tm='tmux'
alias tma='tmux attach-session'
alias tmat='tmux attach-session -t'
alias tmks='tmux kill-session -a'
alias tml='tmux list-sessions'
alias tmn='tmux new-session'
alias tmns='tmux new -s'
alias tms='tmux new-session -s'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
